name: flutter_fusion
description: A flutter project starting point to get started with flutter projects with ease and some awesome built in features.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  http: ^0.13.4
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  ui_x:
    path: packages/ui_x
  connectivity_plus: ^2.3.9
  feather_icons: ^1.2.0
  flutter_local_notifications: ^14.1.1
  # Enable below Firebase related package to use firebase
#  firebase_core:
#  firebase_auth:
#  firebase_messaging:
#  flutter_local_notifications:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  dcli: ^1.36.2
  logger: ^1.4.0
  recase: ^4.1.0
  faker: ^2.1.0

  # Modulr Package to generate Modules
  modulr:
    path: packages/flutter_modulr

# Launcher Icon Configs
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
